"""
sql_preprocessor.py

Transforms original SQL files into SAP B1 SQLQueries API compatible SQL.

SAP B1 limitations handled:
  - No comment lines (-- ...)
  - No quoted/bracket column aliases ('Name' or [Name]) — only simple identifiers
  - No top-level arithmetic in SELECT (*, +, -, /) — operators inside function
    calls like CONCAT(), CAST(), RIGHT() are left as-is
  - No CAST(X AS TYPE) expressions
  - No sized type specifiers like VARCHAR(2)
  - No function calls (YEAR, MONTH, FORMAT, etc.) in GROUP BY / ORDER BY
  - CONCAT(YEAR(date), '-', RIGHT('0'+CAST(MONTH(date) AS ...), 2)) date patterns
    are extracted and computed in Python after fetching

Calculated columns (e.g. Qty * Weight, or CONCAT date expressions) are removed
from the SQL and returned as Python lambdas to be computed after fetching rows.
"""
import re


def _to_identifier(name: str) -> str:
    """'Multi Word Name' or [Multi Word] → MultiWordName."""
    return "".join(w.capitalize() for w in re.split(r"[^a-zA-Z0-9]+", name) if w)


def _is_arithmetic_expr(expr: str) -> bool:
    """
    Return True only if the expression has arithmetic operators (+,-,*,/)
    at the TOP LEVEL — i.e. outside all parentheses (after stripping a single
    outermost wrapping pair).

    Examples:
        "(T1.Qty * T2.Weight)"              → True   (wrapped, * inside)
        "T1.Qty * T2.Weight"                → True   (* at depth 0)
        "SUM(L.Quantity)"                   → False  (inside function)
        "CONCAT(A, '0' + CAST(B AS INT))"   → False  (+ inside CONCAT)
        "YEAR(O.DocDate)"                   → False
    """
    expr = expr.strip()

    # Strip a single fully-wrapping pair of parentheses
    if expr.startswith("(") and expr.endswith(")"):
        depth = 0
        fully_wrapped = True
        for i, ch in enumerate(expr):
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            if depth == 0 and i < len(expr) - 1:
                fully_wrapped = False
                break
        if fully_wrapped:
            expr = expr[1:-1].strip()

    # Check for operators at depth 0 (outside all remaining parentheses)
    depth = 0
    in_string = False
    for ch in expr:
        if ch == "'":
            in_string = not in_string
        if in_string:
            continue
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        elif ch in "+-*/" and depth == 0:
            return True
    return False


def _split_select_columns(select_block: str) -> list[str]:
    """Split SELECT column list on top-level commas (respects parentheses)."""
    columns, current, depth = [], [], 0
    in_string = False
    for ch in select_block:
        if ch == "'":
            in_string = not in_string
        if not in_string:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth -= 1
            elif ch == "," and depth == 0:
                col = "".join(current).strip()
                if col:
                    columns.append(col)
                current = []
                continue
        current.append(ch)
    col = "".join(current).strip()
    if col:
        columns.append(col)
    return columns


# Matches the LAST "AS alias" in a column expression, where alias is:
#   'Quoted Name'  |  [Bracket Name]  |  SimpleWord
_COL_RE = re.compile(
    r"^(.*?)\s+AS\s+(?:'([^']+)'|\[([^\]]+)\]|(\w+))\s*$",
    re.IGNORECASE | re.DOTALL,
)

# Matches FORMAT(T.Col, 'yyyy-MM') — generated by our date-format normalizer
_FORMAT_YM_RE = re.compile(
    r"^FORMAT\s*\(\s*(\w+\.\w+)\s*,\s*'yyyy-MM'\s*\)$",
    re.IGNORECASE,
)


def _make_multiply(a1: str, a2: str):
    return lambda r: (r.get(a1) or 0) * (r.get(a2) or 0)


def _make_date_ym(date_alias: str):
    """Return lambda that extracts 'YYYY-MM' from an ISO date string in a row."""
    def fn(r):
        val = r.get(date_alias)
        if isinstance(val, str) and len(val) >= 7:
            return val[:7]
        return None
    return fn


def preprocess_sql(sql_text: str) -> tuple[str, list[tuple[str, callable]]]:
    """
    Preprocess SQL for SAP B1 SQLQueries compatibility.

    Returns:
        clean_sql   — transformed SQL ready to send to B1
        calc_cols   — list of (column_name, lambda_fn) for post-fetch computation
    """
    # 0. Strip UTF-8 BOM if present
    sql_text = sql_text.lstrip("\ufeff")

    # 0b. SAP B1 does not support bracket-quoted identifiers ([Column], [Table]).
    #     Strip all brackets: [Identifier] → Identifier
    sql_text = re.sub(r"\[([^\]]+)\]", r"\1", sql_text)

    # 1. Remove standalone comment lines and inline trailing comments
    sql = re.sub(r"^\s*--[^\n]*\n?", "", sql_text, flags=re.MULTILINE)
    sql = re.sub(r"\s*--[^\n]*", "", sql)

    # 2. Replace CONCAT(YEAR(X), '-', RIGHT('0' + CAST(MONTH(X) AS ...), 2))
    #    with FORMAT(X, 'yyyy-MM') so we can detect it during column processing.
    sql = re.sub(
        r"CONCAT\s*\(\s*YEAR\s*\(\s*(\w+\.\w+)\s*\)\s*,\s*'-'\s*,"
        r"\s*RIGHT\s*\(\s*'0'\s*\+\s*CAST\s*\(\s*MONTH\s*\(\s*\1\s*\)"
        r"\s+AS\s+\w+(?:\s*\(\s*\d+\s*\))?\s*\)\s*,\s*2\s*\)\s*\)",
        lambda m: f"FORMAT({m.group(1)}, 'yyyy-MM')",
        sql,
        flags=re.IGNORECASE,
    )

    # 3. B1 doesn't support sized type specifiers: VARCHAR(2) → VARCHAR
    sql = re.sub(
        r"\b(N?VARCHAR|N?CHAR|NUMERIC|DECIMAL|FLOAT)\s*\(\s*[\d,\s]+\s*\)",
        lambda m: m.group(1),
        sql,
        flags=re.IGNORECASE,
    )

    # 4. Strip CAST(X AS TYPE) → X  (B1 rejects CAST keyword)
    sql = re.sub(
        r"\bCAST\s*\(\s*([^()]+(?:\([^()]*\)[^()]*)*?)\s+AS\s+\w+\s*\)",
        r"\1",
        sql,
        flags=re.IGNORECASE,
    )

    # 5. Replace YEAR(X), MONTH(X) pairs in GROUP BY / ORDER BY with just X.
    #    B1 doesn't support function calls in GROUP BY or ORDER BY.
    sql = re.sub(
        r"\bYEAR\s*\(\s*(\w+\.\w+)\s*\)\s*,\s*MONTH\s*\(\s*\1\s*\)",
        r"\1",
        sql,
        flags=re.IGNORECASE,
    )

    # 6. Locate the SELECT...FROM block
    select_m = re.search(r"\bSELECT\b(.*?)\bFROM\b", sql, re.IGNORECASE | re.DOTALL)
    if not select_m:
        return sql, []

    select_block = select_m.group(1)
    columns = _split_select_columns(select_block)

    # 7. First pass — build alias_map: "table.col" (lower) → SimpleAlias
    #    Only for non-arithmetic, simple table.col references
    alias_map: dict[str, str] = {}
    for col in columns:
        m = _COL_RE.match(col)
        if not m:
            continue
        expr = m.group(1).strip()
        alias_raw = m.group(2) or m.group(3) or m.group(4) or ""
        simple = _to_identifier(alias_raw)
        if _is_arithmetic_expr(expr):
            continue
        ref = re.match(r"^(\w+\.\w+)$", expr)
        if ref:
            alias_map[expr.lower()] = simple

    # 8. Second pass — build B1-safe column list and capture calc columns
    new_columns: list[str] = []
    calc_cols: list[tuple[str, callable]] = []

    for col in columns:
        m = _COL_RE.match(col)
        if not m:
            col_stripped = col.strip()
            if col_stripped:
                # SAP B1 requires explicit aliases when JOIN tables share column names.
                # Auto-alias Table.Column → Table.Column AS Column.
                tbl_col = re.match(r'^(\w+)\.(\w+)$', col_stripped)
                if tbl_col:
                    new_columns.append(f"{col_stripped} AS {tbl_col.group(2)}")
                else:
                    new_columns.append(col_stripped)
            continue

        expr = m.group(1).strip()
        alias_raw = m.group(2) or m.group(3) or m.group(4) or ""
        simple = _to_identifier(alias_raw)

        if _is_arithmetic_expr(expr):
            # Remove from SQL; build Python lambda for post-fetch computation
            operands = re.findall(r"\w+\.\w+", expr)
            resolved = [alias_map.get(op.lower()) for op in operands if alias_map.get(op.lower())]
            if len(resolved) >= 2 and "*" in expr:
                calc_cols.append((simple, _make_multiply(resolved[0], resolved[1])))
            continue

        # FORMAT(date_col, 'yyyy-MM') — B1 can't run this in GROUP BY,
        # so we add the raw date column to SELECT and compute YearMonth in Python.
        fm = _FORMAT_YM_RE.match(expr)
        if fm:
            date_col_ref = fm.group(1)  # e.g. "O.DocDate"
            date_alias = alias_map.get(date_col_ref.lower())
            if not date_alias:
                date_alias = _to_identifier(date_col_ref.split(".")[-1])
                new_columns.append(f"{date_col_ref} AS {date_alias}")
                alias_map[date_col_ref.lower()] = date_alias
            calc_cols.append((simple, _make_date_ym(date_alias)))
            continue

        # Keep column with a B1-safe alias
        new_columns.append(f"{expr} AS {simple}")

    # 9. Rebuild SQL with the transformed SELECT block
    cols_sql = ",\n    ".join(new_columns)
    clean_sql = (
        sql[: select_m.start(1)]
        + f"\n    {cols_sql}\n"
        + sql[select_m.end(1) :]
    )

    return clean_sql, calc_cols
